use anyhow::{bail, Result};
use colored::Colorize;
use dialoguer::{Confirm, Input, Select};

use crate::config::Config;

const LEGAL_TEXT: &str = r#"
=== Proof@Home Donation Agreement ===

By proceeding, you acknowledge and agree to the following:

1. VOLUNTARY DONATION: You are voluntarily donating a portion of your
   Anthropic API credits toward automated mathematical theorem proving.

2. NON-REFUNDABLE: API credits consumed during proof sessions cannot be
   recovered. You are responsible for monitoring your own Anthropic billing.

3. PUBLIC DOMAIN: All proofs generated through Proof@Home are released
   into the public domain (CC0). You waive all intellectual property
   claims over the generated proof scripts.

4. NO WARRANTY: Proofs are generated by AI and mechanically verified.
   While the formal verification provides mathematical certainty, the
   Proof@Home project makes no warranty about fitness for any purpose.

5. ATTRIBUTION: Your username will be permanently associated with the
   proofs you help generate, recorded in NFT-compatible metadata.
"#;

pub fn run_donate() -> Result<()> {
    if !Config::exists() {
        bail!("No config found. Run `proof-at-home init` first.");
    }

    let mut config = Config::load()?;

    println!("{}", LEGAL_TEXT.dimmed());

    let accepted = Confirm::new()
        .with_prompt("Do you accept the above agreement?")
        .default(false)
        .interact()?;

    if !accepted {
        println!("Donation cancelled.");
        return Ok(());
    }

    let amounts = vec!["$1.00", "$2.00", "$5.00", "$10.00", "Custom amount"];
    let selection = Select::new()
        .with_prompt("How much would you like to donate?")
        .items(&amounts)
        .default(2)
        .interact()?;

    let amount: f64 = match selection {
        0 => 1.0,
        1 => 2.0,
        2 => 5.0,
        3 => 10.0,
        _ => {
            let custom: String = Input::new()
                .with_prompt("Enter amount in USD (e.g. 3.50)")
                .interact_text()?;
            custom
                .trim_start_matches('$')
                .parse::<f64>()
                .map_err(|_| anyhow::anyhow!("Invalid amount"))?
        }
    };

    if amount <= 0.0 {
        bail!("Donation amount must be positive.");
    }

    config.budget.donated_usd = amount;
    config.save()?;

    println!();
    println!(
        "{} Budget set to {}",
        "✓".green().bold(),
        format!("${:.2}", amount).cyan().bold()
    );
    println!(
        "Run {} to start proving theorems!",
        "proof-at-home run".cyan()
    );

    Ok(())
}
